Use new protobuf API instead of deprecated one
This fixes compiler failures like

  error: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated: Please use ByteSizeLong() instead [-Werror=deprecated-declarations]