xocl: Fixes for compilation on kernel 6.16+ (#9411)
* Fix p2p.c compilation on newer kernels

Link: https://git.kernel.org/torvalds/c/6632863226d88
Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>

* Fixups on bin_attribute handling necessary for newer kernels

Newer kernels are more stringent about the use of const.

Link: https://github.com/Xilinx/XRT/issues/9300
Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>

* Add conditional compilation for changes with timer symbols in kernel 6.16

Link: https://git.kernel.org/torvalds/c/41cb08555c416
Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>

* Fix unit type in an snprintf

Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>

* Fix compliation issues with newer gcc with auto variables

  CC [M]  ../../common/kds_hwctx.o
../../common/kds_hwctx.c: In function ‘show_kds_cuctx_stat_raw’:
../../common/kds_hwctx.c:59:41: error: ‘__seg_gs’ specified for auto variable ‘res’
   59 |                                         cu_stat_read(cu_mgmt, usage[i]), type);
      |                                         ^~~~~~~~~~~~
../../common/kds_hwctx.c:99:49: error: ‘__seg_gs’ specified for auto variable ‘res’
   99 |                                                 cu_stat_read(cu_mgmt, usage[i]), type);
      |                                                 ^~~~~~~~~~~~
make[5]: *** [/usr/src/linux-headers-6.17.6+deb14-common/scripts/Makefile.build:292: ../../common/kds_hwctx.o] Error 1

The issue is that the stat_read macro is using typeof on a per-CPU variable field, which newer GCC versions handle
differently for segment-register-based per-CPU variables. The __seg_gs attribute is getting applied to the local
res variable, which is causing a compilation error.

Modify the stat_read macro to avoid the issue with typeof and segment registers.

Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>

* Handle namespace import change from kernel 6.13

Link: https://github.com/torvalds/linux/commit/cdd30ebb1b9f36159d66f088b61aee264e649d7a
Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>

* Handle removal of linux/pfn_t.h in newer kernels

Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>

* Handle changes for xocl drm for current kernel

Link: https://git.kernel.org/torvalds/c/cb2e1c2136f7
Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>

* Handle CRC symbol move

Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>

* Apply review comments

- BIN_ATTRIBUTE_CONST conditional for v6.16+
- del_timer_sync() conditional for v6.15-
- fcheck backported to v5.10.220

Signed-off-by: Soren Soe <2106410+stsoe@users.noreply.github.com>

---------

Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>
Signed-off-by: Soren Soe <2106410+stsoe@users.noreply.github.com>
Co-authored-by: Soren Soe <2106410+stsoe@users.noreply.github.com>