xbtracer: exclude Protobuf to JSON conversion by default
Replay can dump JSON message when it fails to replay the function
captured in Protobuf stream. And we have a helper tool to dump
the generated Protobuf XRT APIs sequence in JSON format.
However, calling this function:
ROTOBUF_EXPORT absl::Status MessageToJsonString()
causes an issue in APU versal CI yocto build:
 undefined reference to symbol '_ZNK4absl12lts_2024011615status_internal9StatusRep5UnrefEv'
aarch64-amd-linux/13.3.0/ld: recipe-sysroot/usr/lib/libabsl_status.so.2401.0.0: error adding symbols: DSO missing from command line
Will need to check the yocto build to solve the protobuf and absl
mismatching issue.
Other build systems doesn't have this issue.

For now, as converting to JSON not the key feature for xbtracer/replay,
it is disabled by default.
Will reenalbe it once the yocto build failure is fixed.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>