Fix compliation issues with newer gcc with auto variables
  CC [M]  ../../common/kds_hwctx.o
../../common/kds_hwctx.c: In function ‘show_kds_cuctx_stat_raw’:
../../common/kds_hwctx.c:59:41: error: ‘__seg_gs’ specified for auto variable ‘res’
   59 |                                         cu_stat_read(cu_mgmt, usage[i]), type);
      |                                         ^~~~~~~~~~~~
../../common/kds_hwctx.c:99:49: error: ‘__seg_gs’ specified for auto variable ‘res’
   99 |                                                 cu_stat_read(cu_mgmt, usage[i]), type);
      |                                                 ^~~~~~~~~~~~
make[5]: *** [/usr/src/linux-headers-6.17.6+deb14-common/scripts/Makefile.build:292: ../../common/kds_hwctx.o] Error 1

The issue is that the stat_read macro is using typeof on a per-CPU variable field, which newer GCC versions handle
differently for segment-register-based per-CPU variables. The __seg_gs attribute is getting applied to the local
res variable, which is causing a compilation error.

Modify the stat_read macro to avoid the issue with typeof and segment registers.

Signed-off-by: Mario Limonciello (AMD) <superm1@kernel.org>