Update xbtracer/replay prototype to use protobuf for tracking XRT CPP APIs and use Microsoft Detours to hook XRT APIs in Windows (#9065)
* core: tools: CMakeLists: remove xbreplay

Remove building the old xbreplay, in the new implementation, both
xbtracer and replay will be in the same directory.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer/xbreplay: Remove old implementation

Remove old xbtracer/xbreplay implementation to shift to updated
xbtracer/xbreplay implementation.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: implementation print and common utils

Add xbtracedr directory for the future updated xbtracer implementation.
Add logger to print debugging information and implement common utils
used by the logger. The tracing implementation will be in future commits.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: common: add linux mangled function name lookup

Add linux mangled functions names mapping table and lookup implementation.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: common: add win utils and mangled functions names lookup

Add windows common utils and mangled functions names mapping table
and lookup implementation.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: add funtions messagess protobuf schema

We are using protobuf to record the XRT functions calls sequences and
its parameters, later the replayer can read the messages from the protobuf
stream to get the call sequence and the parameters, and then it can replay
the XRT calling sequence with these information.

This patch is to define the protobuf schema for the XRT functions.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: CMake: generate protobuf files

Implement CMakeLists.txt to generate required protobuf headers and cpp
files for xbtracer.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: wrapper: add initial tracer library

Add initial tracer library implementation to implement tracer to
* track XRT APIs entries and exits to protobuf stream
* do not track XRT APIs to protobuf stream if they are called from
  another XRT APIs.
  * Use PID to know if the XRT API is called from another XRT APIs
    or not. IF an XRT API is called from user application, it will
    track its PID, when any XRT API is called, it will check if its
    PID has been tracked, if yes, it means it is called from another
    XRT API, no track this API. When the tracked API exits, untrack
    its PID.
* track XRT class objects lifetime using its pimpl handle, each class
  objects has a pimpl handle. Whenever a constructor is called, tracer
  tracks its pimpl shared pointer, whenever any XRT API is called, tracer
  checks all the tracked pimpl handles to see if anyone is using it. if
  not, it will inject a destructor call in the protobuf stream.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: Add windows detours submodule

Add Windows detours submodule as we are going to use it to hook XRT APIs
in Windows.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: wrapper: add windows tracer implementation

Use Windows Detours to hook to XRT APIs and track API calling sequence.
Also hook CreateProcess Windows APIs as in cases the target app is wrapped
with .bat file.

Detours is a software packaged maintained by Microsoft which can be used
to monitor and instrument Windows APIs. Please see
https://github.com/microsoft/Detours for details.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: wrapper: add initial XRT APIs hooking functions

Add initial XRT APIs hooking functions implementation.
This initial implementation will track the API function call
entries and exits with function signatures and the member functions
pimpl handle.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: wrapper: xrt hooking function disable some lint checking

Disable some lint checking.
* the hooking functions will call the actual funciton from xrt_coreutil
  passing the input arguments. disabling lint check to avoid clangtidy
  check warning.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: wrapper: hook APIs: initial parameters capture

Implment minimum set of XRT APIs hooking functions to capture
parameters for a simplest XCLBIN flow XRT calling sequence:
* create a device
* register xclbin
* open hw context
* create kernel object based
* creat in/out BOs
* sync BO data
* run kernel with input data
* wait for run to finish
* sync output BO data

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: capture: add initial xbtracer main implementation

Add initial xbtracer main application implementation to
enable user to trace their XRT API calling sequence.

e.g.
 xbtracer <APP> [APP_ARGS]

or verbose mode:
 xbtracer -v <APP> [APP_ARGS]
which outputs xbtracer debugging information.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: capture: add initial windows implementation

Add initial windows tracer implementation, as Windows uses Detours,
and Windows doesn't have LD_PRELOAD, will need to inject xrt_wrapper
library when it creae process for the target application.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: replay: add initial replay basic implementation

Add initial replay top level implementation.
Here is the replayh flow:
* it reads protobuf messages streams from user specified file and
  push to a message queue
* a worker thread is listening on the message queue. Use a worker
  thread is to enable future capability to replay multi threads
  XRT applications.
* the working threads reads a message, parse the message, gets
  the function signature and the parameters,  and then calls
  the coresponding XRT APIs to replay the sequence.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: replay: implement minimum XRT APIs replay functions

Implement the minimum sets of XRT APIs replay parser functions
to replay the simplest XCLBIN XRT calling sequence.
It implement the following XRT APIs replay parsing functions:
* device creation
* xclbin creation
* xclbin registration
* xclbin kernel query
* hw context creation
* kernel creation
* bo creation
* bo sync
* bo size
* bo mmap
* run creation
* run start, wait

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: CMake: Add buildign Detours CMake module

Add a CMake module to build Detours library.
Detours uses Makefile by default, and it builds the
library and all examples and tests all the time, which takes long time.
Introduce this CMake module referring to other github Detours
CMake example to build the library only.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: add tracer/replay windonws .bat file

To align with other XRT tools, add .bat file for tracer and replay.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: CMake: Add CMakeLists.txt for tracer/replay

Add CMakeLists.txt file to build tracer/replay.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: add script for mangled names mapping and XRT hooking functions generation

This patch adds the helper script which is used to:
* generate the functions signature to mangled names mapping for Linux and Windows
* basic hooking functions gneeration for all exposed XRT cpp APIs which captures
  function entry/exit and the class object pimpl handle.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: add addtional helper tool to dump protobuf messages

Add additional helper tool to dump XRT APIs protobuf messages in
JSON format.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: CMakeLists: Build helper to dump protobuf msg in JSON

Enable to build xbtracer helper tool to dump XRT APIs protobuf messages
in JSON format.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

* xbtracer: exclude Protobuf to JSON conversion by default

Replay can dump JSON message when it fails to replay the function
captured in Protobuf stream. And we have a helper tool to dump
the generated Protobuf XRT APIs sequence in JSON format.
However, calling this function:
ROTOBUF_EXPORT absl::Status MessageToJsonString()
causes an issue in APU versal CI yocto build:
 undefined reference to symbol '_ZNK4absl12lts_2024011615status_internal9StatusRep5UnrefEv'
aarch64-amd-linux/13.3.0/ld: recipe-sysroot/usr/lib/libabsl_status.so.2401.0.0: error adding symbols: DSO missing from command line
Will need to check the yocto build to solve the protobuf and absl
mismatching issue.
Other build systems doesn't have this issue.

For now, as converting to JSON not the key feature for xbtracer/replay,
it is disabled by default.
Will reenalbe it once the yocto build failure is fixed.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>

---------

Signed-off-by: Wendy Liang <wendy.liang@amd.com>