Various build fixes (#1069)
* Work around GCC not fully knowing host_ptr is nonnull

Compilation with GCC 8.3.0 and -Wall hits:

src/runtime_src/xocl/core/memory.h:492:18: error: argument 2 null where
non-null expected [-Werror=nonnull]
       std::memcpy(m_host_ptr,host_ptr,sz);
       ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

host_ptr is checked earlier in the instances I can see, but doing the
additional check here silences GCC without losing the check.

* Avoid truncation warnings with more recent GCC version

GCC 8.3.0 is stricter on truncation warnings when using the str*
functions. In particular the length for strncpy() must be one less
than the total length, to allow for the trailing NULL. Fixes the
following build failures:

src/runtime_src/driver/xclng/xrt/user_gem/perf.cpp:1016:12: error:
‘char* strncpy(char*, const char*, size_t)’ specified bound 256 equals
destination size [-Werror=stringop-truncation]

     strncpy(info->device_name, device_name.c_str(), MAX_NAME_LEN);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/xma/src/xmaapi/xmalogger.cpp:207:16: error: ‘char* strncpy(char*,
const char*, size_t)’ specified bound 40 equals destination size
[-Werror=stringop-truncation]

         strncpy(log_name, name, sizeof(log_name));
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* Fix use of local kernel-doc copy

The build fetches a local copy of kernel-doc if a system copy is not
found, but then stores a relative path to it which causes a build issue
when it is used. Fixes:

/bin/sh: 1: ./kernel-doc: not found
make[2]: *** [runtime_src/doc/CMakeFiles/xrt_docs.dir/build.make:90:
              runtime_src/doc/core/xmaplugin.rst] Error 127
make[2]: *** Deleting file 'runtime_src/doc/core/xmaplugin.rst'
make[1]: *** [CMakeFiles/Makefile2:315:
              runtime_src/doc/CMakeFiles/xrt_docs.dir/all] Error 2